import {chromium} from '@playwright/test';
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173');
await page.getByPlaceholder('搜索书名、作者或 ISBN').fill('百年');
if(await page.locator('.book-card').count()!==1)throw Error('Search failed');
await page.getByPlaceholder('搜索书名、作者或 ISBN').fill('');
await page.getByRole('button',{name:'新增图书',exact:true}).click();
await page.getByPlaceholder('例如：追风筝的人').fill('验证图书');
await page.getByPlaceholder('请输入作者姓名').fill('验证作者');
await page.getByRole('button',{name:'确认添加'}).click();
await page.locator('.book-card').filter({hasText:'验证图书'}).getByRole('button',{name:'借阅',exact:true}).click();
await page.locator('.sidebar').getByRole('button',{name:'借阅记录'}).click();
await page.getByRole('row').filter({hasText:'验证图书'}).getByRole('button',{name:'归还'}).click();
await page.locator('.sidebar').getByRole('button',{name:'概览',exact:true}).click();
await page.reload();
if(!await page.getByRole('heading',{name:'验证图书'}).count())throw Error('Persistence failed');
await page.evaluate(()=>localStorage.removeItem('zhiye-data'));await page.reload();
await page.screenshot({path:'desktop-preview.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'mobile-preview.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
if(errors.length)throw Error(errors.join('\n'));
console.log('PASS: search, add, borrow, return, persistence, mobile layout');await browser.close();
