<script setup>
import {computed, ref, watch} from 'vue'
import {BookOpen, LayoutDashboard, Library, Users, ClipboardList, Settings, Search, Bell, Plus, Filter, MoreHorizontal, ArrowUpRight, Clock3, CheckCircle2, BookMarked, X, ChevronDown, RotateCcw, UserRound, Sparkles} from 'lucide-vue-next'

const active=ref('概览'); const query=ref(''); const category=ref('全部分类'); const showAdd=ref(false); const showReaders=ref(false); const toast=ref(''); const role=ref('管理员')
const categories=['全部分类','文学小说','人文社科','科学技术','少儿读物']
const books=ref([
 {id:1,title:'百年孤独',author:'加西亚·马尔克斯',category:'文学小说',isbn:'978-7-02-000220-7',status:'在馆',color:'#dcebe4',cover:'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=240&q=80'},
 {id:2,title:'人类简史',author:'尤瓦尔·赫拉利',category:'人文社科',isbn:'978-7-5086-6105-3',status:'借出',color:'#e8e1d2',cover:'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=240&q=80'},
 {id:3,title:'置身事内',author:'兰小欢',category:'人文社科',isbn:'978-7-108-07224-5',status:'在馆',color:'#dfe7ed',cover:'https://images.unsplash.com/photo-1550399105-c4db5fb85c18?w=240&q=80'},
 {id:4,title:'小王子',author:'安托万·德·圣-埃克苏佩里',category:'少儿读物',isbn:'978-7-5327-5087-8',status:'在馆',color:'#f0e1d1',cover:'https://images.unsplash.com/photo-1629992101753-56d196c8aabb?w=240&q=80'},
 {id:5,title:'三体',author:'刘慈欣',category:'科学技术',isbn:'978-7-5366-9293-0',status:'借出',color:'#e7d9e4',cover:'https://images.unsplash.com/photo-1614728263952-84ea256f9679?w=240&q=80'},
 {id:6,title:'云边有个小卖部',author:'张嘉佳',category:'文学小说',isbn:'978-7-5594-3638-1',status:'在馆',color:'#e5e5d6',cover:'https://images.unsplash.com/photo-1511108690759-009324a90311?w=240&q=80'}
])
const readers=ref([{id:1,name:'周子涵',phone:'13800001234'},{id:2,name:'陈默',phone:'13900005678'},{id:3,name:'赵一鸣',phone:'13700009012'}]);const records=ref([]);const editId=ref(null);const readerName=ref('');const readerPhone=ref('');const selectedReader=ref(1);const recordFilter=ref('全部');
try{const saved=JSON.parse(localStorage.getItem('zhiye-data'));if(saved){books.value=saved.books;readers.value=saved.readers;records.value=saved.records}}catch{}
watch([books,readers,records],()=>localStorage.setItem('zhiye-data',JSON.stringify({books:books.value,readers:readers.value,records:records.value})),{deep:true});
const admin=computed(()=>role.value==='管理员');
const visibleRecords=computed(()=>records.value.filter(r=>(admin.value||r.readerId===1)&&(recordFilter.value==='全部'||r.status===recordFilter.value)));
const newBook=ref({title:'',author:'',category:'文学小说'})
const filtered= computed(()=>books.value.filter(b=>(category.value==='全部分类'||b.category===category.value)&&(`${b.title}${b.author}${b.isbn}`.toLowerCase().includes(query.value.toLowerCase()))))
const stats=computed(()=>[{label:'馆藏图书',value:books.value.length+'+',change:'+12%',icon:Library,tone:'mint'},{label:'本月借阅',value:'1,284',change:'+8.6%',icon:BookMarked,tone:'blue'},{label:'活跃读者',value:'638',change:'+4.2%',icon:Users,tone:'sand'},{label:'待处理归还',value:'27',change:'需关注',icon:Clock3,tone:'rose'}])
function notify(msg){toast.value=msg;setTimeout(()=>toast.value='',2200)}
function borrow(book){const mine=records.value.find(r=>r.bookId===book.id&&r.status==='借阅中');if(book.status==='借出'){if(!admin.value&&(!mine||mine.readerId!==1)){notify('仅管理员或借阅本人可归还');return}book.status='在馆';if(mine){mine.status='已归还';mine.returned=new Date().toLocaleDateString('zh-CN')}notify(`《${book.title}》已完成归还`)}else{const reader=readers.value.find(r=>r.id===(admin.value?Number(selectedReader.value):1));if(!reader){notify('请先添加读者');return}book.status='借出';records.value.unshift({id:Date.now(),bookId:book.id,title:book.title,readerId:reader.id,name:reader.name,date:new Date().toLocaleDateString('zh-CN'),due:new Date(Date.now()+30*86400000).toLocaleDateString('zh-CN'),status:'借阅中'});notify(`《${book.title}》已借出给${reader.name}`)}}
function editBook(book){if(!admin.value)return;editId.value=book.id;newBook.value={title:book.title,author:book.author,category:book.category};showAdd.value=true}
function addBook(){if(!admin.value)return;if(!newBook.value.title.trim()||!newBook.value.author.trim()){notify('请填写书名和作者');return}if(editId.value){Object.assign(books.value.find(b=>b.id===editId.value),newBook.value)}else{books.value.unshift({id:Date.now(),...newBook.value,isbn:'待录入',status:'在馆',color:'#dcebe4',cover:'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=240&q=80'})}showAdd.value=false;editId.value=null;newBook.value={title:'',author:'',category:'文学小说'};notify('图书信息已保存')}
function openAdd(){if(!admin.value)return;editId.value=null;newBook.value={title:'',author:'',category:'文学小说'};showAdd.value=true}
function addReader(){if(!admin.value)return;if(!readerName.value.trim()||!/^1\d{10}$/.test(readerPhone.value)){notify('请输入姓名和11位手机号');return}readers.value.push({id:Date.now(),name:readerName.value.trim(),phone:readerPhone.value});readerName.value='';readerPhone.value='';notify('读者已添加')}
function deleteBook(book){if(!admin.value)return;if(book.status==='借出'){notify('借出的图书须先归还');return}if(confirm(`确认删除《${book.title}》？`))books.value=books.value.filter(b=>b.id!==book.id)}
</script>

<template>
<div class="app-shell">
 <aside class="sidebar">
  <div class="brand"><div class="brand-mark"><BookOpen :size="20"/></div><div><strong>知页</strong><span>ZH IYE LIBRARY</span></div></div>
  <div class="workspace"><div class="avatar">Z</div><div><b>知页图书馆</b><small>总馆 · 运营工作台</small></div><ChevronDown :size="15"/></div>
  <p class="nav-label">工作台</p>
  <nav><button v-for="item in [{n:'概览',i:LayoutDashboard},{n:'图书管理',i:Library},{n:'借阅记录',i:ClipboardList},{n:'读者管理',i:Users}]" :key="item.n" :class="{active:active===item.n}" @click="active=item.n"><component :is="item.i" :size="18"/>{{item.n}}<span v-if="item.n==='借阅记录'" class="nav-count">27</span></button></nav>
  <p class="nav-label lower">系统</p><nav><button :class="{active:active==='设置'}" @click="active='设置'"><Settings :size="18"/>系统设置</button></nav>
  <div class="sidebar-foot"><div class="status-dot"></div><span>系统运行正常</span><span class="version">v2.4.1</span></div>
 </aside>
 <main class="main"><nav class="mobile-nav"><button v-for="n in ['概览','图书管理','借阅记录','读者管理','设置']" @click="active=n" :key="n">{{n}}</button></nav>
  <header class="topbar"><div class="crumb">工作台 <span>/</span> {{active}}</div><div class="top-actions"><div class="role-switch"><UserRound :size="15"/><select v-model="role"><option>管理员</option><option>读者</option></select></div><button class="icon-btn" title="通知"><Bell :size="18"/><i></i></button><div class="profile"><div class="profile-avatar">林</div><div><b>林知夏</b><small>管理员</small></div><ChevronDown :size="14"/></div></div></header>
  <section class="content" v-if="active==='概览'||active==='图书管理'">
   <div class="welcome"><div><div class="eyebrow"><Sparkles :size="14"/> 知页 · 校园图书馆</div><h1>{{active==='概览'?'你好，林知夏':'图书管理'}}<span>。</span></h1><p>书页之间，遇见更大的世界。</p></div><button v-if="admin" class="primary" @click="openAdd"><Plus :size="17"/>新增图书</button></div>
   <div class="stat-grid"><div class="stat-card" v-for="s in stats" :key="s.label"><div class="stat-top"><span>{{s.label}}</span><div :class="['stat-icon',s.tone]"><component :is="s.icon" :size="18"/></div></div><div class="stat-value">{{s.value}}</div><div class="stat-change"><ArrowUpRight :size="14"/>{{s.change}} <span>较上月</span></div></div></div>
   <div class="section-head"><div><h2>馆藏图书</h2><p>共 {{books.length+1248}} 本图书，实时更新</p></div><div class="head-actions"><div class="search"><Search :size="17"/><input v-model="query" placeholder="搜索书名、作者或 ISBN"/></div><div class="select-wrap"><Filter :size="15"/><select v-model="category"><option v-for="c in categories" :key="c">{{c}}</option></select></div><button class="more-btn" @click="notify('筛选条件已保存')"><MoreHorizontal :size="20"/></button></div></div>
   <div v-if="admin" class="lending-select"><label>借阅读者 <select v-model="selectedReader"><option v-for="r in readers" :value="r.id" :key="r.id">{{r.name}}</option></select></label></div>
   <div class="book-grid"><article class="book-card" v-for="book in filtered" :key="book.id"><div class="cover" :style="{backgroundColor:book.color}"><img :src="book.cover" :alt="book.title+'馆藏配图'"/><span :class="['book-status',book.status==='在馆'?'available':'borrowed']"><span></span>{{book.status}}</span></div><div class="book-info"><div><h3>{{book.title}}</h3><p>{{book.author}}</p></div><button v-if="admin" class="tiny-more" title="编辑图书" @click="editBook(book)"><MoreHorizontal :size="17"/></button></div><div class="book-meta"><span>{{book.category}}</span><span>{{book.isbn}}</span></div><button class="borrow-btn" @click="borrow(book)"><RotateCcw :size="14"/>{{book.status==='在馆'?'借阅':'归还'}}</button><button v-if="admin&&active==='图书管理'" class="delete-link" @click="deleteBook(book)">删除图书</button></article><div v-if="!filtered.length" class="empty">没有找到相关图书</div></div>
   <div class="bottom-grid"><div class="panel activity"><div class="panel-head"><div><h2>最近借阅</h2><p>今日动态</p></div><button @click="active='借阅记录'">查看全部 <ArrowUpRight :size="15"/></button></div><div class="activity-row" v-for="a in [{name:'周子涵',book:'《人类简史》',time:'10分钟前',type:'借阅',color:'blue'},{name:'陈默',book:'《置身事内》',time:'32分钟前',type:'归还',color:'green'},{name:'赵一鸣',book:'《三体》',time:'1小时前',type:'借阅',color:'orange'}]" :key="a.name"><div :class="['mini-avatar',a.color]">{{a.name[0]}}</div><div><b>{{a.name}}</b><span>{{a.type}}{{a.book}}</span></div><time>{{a.time}}</time></div></div><div class="panel readers"><div class="panel-head"><div><h2>读者概况</h2><p>本月活跃度</p></div><button @click="showReaders=true">管理读者 <ArrowUpRight :size="15"/></button></div><div class="reader-number"><strong>638</strong><span>位活跃读者</span></div><div class="chart"><i v-for="h in [35,52,45,68,58,81,65,91,72,84,76,96]" :style="{height:h+'%'}" :key="h"></i></div><div class="chart-labels"><span>1日</span><span>7日</span><span>14日</span><span>21日</span><span>今日</span></div></div></div>
  </section>
  <section class="content" v-else-if="active==='借阅记录'"><h1>借阅记录</h1><p class="subtle">借阅与归还明细</p><select v-model="recordFilter"><option>全部</option><option>借阅中</option><option>已归还</option></select><div class="table-scroll"><table><thead><tr><th>图书</th><th>读者</th><th>借阅日期</th><th>应还日期</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="r in visibleRecords" :key="r.id"><td>{{r.title}}</td><td>{{r.name}}</td><td>{{r.date}}</td><td>{{r.due}}</td><td>{{r.status}}</td><td><button v-if="r.status==='借阅中'" class="borrow-btn" @click="borrow(books.find(b=>b.id===r.bookId))">归还</button><span v-else>{{r.returned}}</span></td></tr></tbody></table><p v-if="!visibleRecords.length" class="empty">暂无借阅记录</p></div></section>
  <section class="content" v-else-if="active==='读者管理'"><h1>读者管理</h1><p class="subtle">{{admin?'读者档案':'我的读者档案'}}</p><form v-if="admin" class="reader-form" @submit.prevent="addReader"><input v-model="readerName" placeholder="读者姓名" aria-label="读者姓名" required/><input v-model="readerPhone" placeholder="11位手机号" aria-label="手机号" required/><button class="primary">新增读者</button></form><div class="table-scroll"><table><thead><tr><th>姓名</th><th>手机号</th><th>在借图书</th><th>读者状态</th></tr></thead><tbody><tr v-for="r in readers.filter(r=>admin||r.id===1)" :key="r.id"><td>{{r.name}}</td><td>{{r.phone}}</td><td>{{records.filter(x=>x.readerId===r.id&&x.status==='借阅中').length}}</td><td><span class="available">正常</span></td></tr></tbody></table></div></section>
  <section class="content" v-else><h1>系统设置</h1><p class="subtle">知页图书馆 · 本地工作台</p><div class="settings-row"><span>当前身份</span><select v-model="role"><option>管理员</option><option>读者</option></select></div><div class="settings-row"><span>借阅期限</span><b>30天</b></div><div class="settings-row"><span>数据保存</span><b>此浏览器本地保存</b></div></section>
 </main>
 <transition name="fade"><div v-if="toast" class="toast"><CheckCircle2 :size="18"/>{{toast}}</div></transition>
 <div class="modal-backdrop" v-if="showAdd" @click.self="showAdd=false"><div class="modal"><button class="modal-close" @click="showAdd=false"><X :size="18"/></button><div class="modal-icon"><Plus :size="20"/></div><h2>新增图书</h2><p>录入一本新书到馆藏中</p><label>书名<input v-model="newBook.title" placeholder="例如：追风筝的人"/></label><label>作者<input v-model="newBook.author" placeholder="请输入作者姓名"/></label><label>分类<select v-model="newBook.category"><option v-for="c in categories.slice(1)" :key="c">{{c}}</option></select></label><button class="primary full" @click="addBook">确认添加 <Plus :size="16"/></button></div></div>
 <div class="modal-backdrop" v-if="showReaders" @click.self="showReaders=false"><div class="modal reader-modal"><button class="modal-close" @click="showReaders=false"><X :size="18"/></button><div class="modal-icon"><Users :size="20"/></div><h2>读者管理</h2><p>当前共有 638 位活跃读者</p><div class="reader-list"><div v-for="r in ['周子涵','陈默','赵一鸣','苏晚']" :key="r"><span class="mini-avatar green">{{r[0]}}</span><b>{{r}}</b><em>正常</em></div></div><button class="primary full" @click="showReaders=false">完成</button></div></div>
</div></template>
